advanced_class_view/advanced_class_view/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import urls, views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('basic_app/',include("basic_app.urls", namespace='basic_app')),
    path('hell/',views.CBView.as_view()),
    path('temp/',views.IndexView.as_view()),
]

advanced_class_view/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('list/<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('list/',views.SchoolListView.as_view(), name='list'),
    path('create/',views.SchoolCreateView.as_view(),name='create'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/',views.SchoolDeleteView.as_view(), name='delete'),
]

advanced_class_view/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('basic_app:detail', kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

advanced_class_view/basic_app/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic import (View, TemplateView, ListView, DetailView,
                                CreateView, UpdateView, DeleteView)        
from django.http import HttpResponse
from .models import School, Student
from django.urls import reverse_lazy
# Create your views here.
class CBView(View):
    def get(self, request):
        return HttpResponse("Class based views!")

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'BASIC INJECTION!'
        return context

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = School
    # school_list

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = School
    template_name = 'basic_app/school_details.html'


class SchoolCreateView(CreateView):
    fields=('__all__')
    model = School

class SchoolUpdateView(UpdateView):
    fields=('name','principal')
    model = School

class SchoolDeleteView(DeleteView):
    model = School
    success_url = reverse_lazy('basic_app:list3')

advanced_class_view/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title></title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class='nav navbar-nav'>
            <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">School</a></li>
            <li><a class="nav-link " href="{% url 'admin:index' %}">Admin</a></li>
        </ul>
    </nav>
    <div class="container">
        {% block body_block%}
        {% endblock %}
    </div>
</body>
</html>

advanced_class_view/basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
<h1>Delete {{school.name}}?</h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="delete">
    <a href="{% url 'basic_app:detail' pk=school.pk %}" class="btn btn-light">Cancel</a>

</form>
{% endblock %}

advanced_class_view/basic_app/templates/basic_app/school_details.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
<div class="jumbotron">
    <h1>Welcome to the school detail page</h1>
    <h2>School Details:</h2>
    <p>Name: {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.loaction}}</p>
    <h3>Students:</h3>

    {% for student in school_detail.students.all%}
     <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}
</div>

<div class="container">
    <p><a href="{% url 'basic_app:update' pk=school_detail.pk %}" class="btn btn-warning">Update</a></p>
</div>
{% endblock %}

advanced_class_view/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}

<h1>
    {% if not form.instance.pk %}
    Create school
    {% else %}
    Update school
    {% endif %}
</h1>
   <form method="post">
     {% csrf_token %}
     {{ form.as_p }}
     <input type="submit" class="btn btn-primary" value="submit">
   </form>
{% endblock %}

advanced_class_view/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
<div class="jumbotron">
<h1>Welcome to a list of all the schools</h1>
<ol>
    {% for school in schools %}
    <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
    {% endfor %}
</ol>
</div>
{% endblock %}

advanced_class_view/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title></title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class='nav navbar-nav'>
            <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">School</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        </ul>
    </nav>
    <div class="container">
        {% block body_block%}
        {% endblock %}
    </div>
</body>
</html>

advanced_class_view/templates/index.html
{% extends "base.html" %}
{% block body_block %}
<h1>Testing TemplateView!</h1>
<h2>Injected Content: {{ injectme }}</h2>
{% endblock %}